# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-07-18 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Company_Name',
            field=models.CharField(max_length=50),
        ),
    ]
